### ISSUE TITLE
use personnal config for prettycss cli

### ISSUE THREAD

**Issue by brunob** [fidian/PrettyCSS#26]
Hi @fidian and thanks for PrettyCSS, this is not an issue just a question.

I've got a personal config with options that suite to my needs if i use the exemple page provided. How can i specify this options when using prettycss form the command line (i mean use other options that the ones specified in lib/utils.js) ?

Thanks ++

**Comment by brunob** [comment]
@fidian ftr my config file listed here doesn't work anymore with 0.3.15 version, seems to have problem with atblock_pre/post :\ It prints things like that : 

```
OUT for block
color: #52a624; 
!!!done`
```

I'm looking to the diff to search the origin of the bug https://github.com/fidian/PrettyCSS/compare/0.3.12...fidian:0.3.15

**Comment by fidian** [comment]
Would you open a new issue so we can discuss it there?

**Comment by brunob** [comment]
For sure #52 :)
