### ISSUE TITLE
Very nice project.

### ISSUE THREAD

**Issue by szepeviktor** [fidian/PrettyCSS#35]
It is possible to fine-tune the output:
```json
{
    "selector_comma": ",\n"
}
```

**Comment by fidian** [comment]
Agreed.  This is detailed more in [Beautifier Options](https://github.com/fidian/PrettyCSS/blob/master/docs/BeautifierOptions.md).

Did you have a question regarding this tool?

**Comment by szepeviktor** [comment]
No, thank you.
