### ISSUE TITLE
Shorthand property 'border-style' causes warning

### ISSUE THREAD

**Issue by Markus00000** [fidian/PrettyCSS#36]
* {
        border-style: none solid dotted dashed;
    }

PrettyCSS gives this warning:

    Extra tokens were found after a valid value - browsers may discard this entire property (solid)

https://developer.mozilla.org/en-US/docs/Web/CSS/border-style

**Comment by fidian** [comment]
You're totally right.  I've just addressed this in the code.

**Comment by fidian** [comment]
Please let me know if this does not work for you.  I've added some tests to make sure that it should work as expected using CSS very similar to what you posted in this bug report.
