### ISSUE TITLE
New website address

### ISSUE THREAD

**Issue by szepeviktor** [fidian/PrettyCSS#37]
Could please fix it: http://www.fidian.com/prettycss

**Comment by fidian** [comment]
What file in particular are you asking me to update?

I think I would prefer the GitHub project to be the source of the documentation.  I was taking it off of fidian.com and moving it into the repository as markdown.

**Comment by fidian** [comment]
Looks like my commit closed the issue unintentionally.

If you wanted me to update package.json, then perhaps this change is acceptable to you?

**Comment by szepeviktor** [comment]
I was thinking about the repo url here at the top: https://github.com/fidian/PrettyCSS

**Comment by szepeviktor** [comment]
This is how it has closed: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by fidian** [comment]
Removed the website address.  Thanks for pointing this out.
