### ISSUE TITLE
HSL/HSLa colors produce warnings

### ISSUE THREAD

**Issue by Markus00000** [fidian/PrettyCSS#39]
Hue is an angle between 0° and 360°. Alpha is between 0 and 1.

https://developer.mozilla.org/en/docs/Web/CSS/color_value#hsl()
https://developer.mozilla.org/en/docs/Web/CSS/color_value#hsla()

Example:

    #test {
        /* You are not allowed to mix percentages with non-percentage values (hsl() [css/prettycss] */
        background-color: hsl(100, 50%, 50%);
        /* You are not allowed to mix percentages with non-percentage values (hsla() [css/prettycss] */
        color: hsla(100, 50%, 50%, 1);
        /* The maximum value allowed is 255 (255) [css/prettycss] */
        color: hsl(300, 50%, 50%);

    }

**Comment by fidian** [comment]
Thanks for finding and reporting this issue!

**Comment by fidian** [comment]
Released 0.3.11, which includes this fix.
