### ISSUE TITLE
Save cli warning and errors output to a file

### ISSUE THREAD

**Issue by s10wen** [fidian/PrettyCSS#40]
I've read;
https://github.com/fidian/PrettyCSS/blob/master/docs/CommandLine.md

and using;
```
prettycss myfile.css > myfile_pretty.css
```

Which logs the errors/warnings in iTerm and then the `myfile_pretty.css` is empty.

Is it possible to run a command to save the errors/warnings into a file please?

**Comment by fidian** [comment]
That is a good suggestion for an additional argument for the command line program, so I've made issue #41.  Right now the errors and warnings are sent to stdout, which you can capture to a file pretty easily.

    # Everything outputs to screen
    prettycss myfile.css

    # Capture CSS to output file
    prettycss myfile.css > myfile_pretty.css

    # Capture CSS to one file, errors to another
    prettycss myfile.css > myfile_pretty.css 2> myfile_errors_and_warnings.txt

    # Only capture errors and warnings
    prettycss myfile.css 2> myfile_errors_and_warnings.txt

Does this solve your current needs?

**Comment by s10wen** [comment]
```
prettycss myfile.css 2> myfile_errors_and_warnings.txt
```

Did exactly what I was after, many thanks :dancer:
