### ISSUE TITLE
Live demo appears to be broken

### ISSUE THREAD

**Issue by RoyTinker** [fidian/PrettyCSS#49]
The "After" area remains blank, even after entering a valid CSS rule in the Before box.

Tested in Chrome, Firefox, and Edge.

![image](https://cloud.githubusercontent.com/assets/984080/24725962/6f60735a-1a05-11e7-9983-8c4e18888ac8.png)

**Comment by RoyTinker** [comment]
Looks like the issue is the MIME type the .js files are being served with is `text/plain`
![image](https://cloud.githubusercontent.com/assets/984080/24726138/271dd87a-1a06-11e7-931c-6ec798ff7d4e.png)

**Comment by mgol** [comment]
Switching the domain from `raw.github.com` to `rawgit.com` should fix the issues.

**Comment by fidian** [comment]
@RoyTinker Thanks for looking into this issue a year ago. Sorry I didn't get to it. :-(

@mgol Excellent idea. I've implemented it.

![image](https://user-images.githubusercontent.com/428348/38556003-c295b48a-3c8d-11e8-8499-9f676e2c1cfe.png)

**Comment by mgol** [comment]
@fidian Just one note: https://rawgit.com [caches files *permanently* based on the URL path](https://github.com/rgrove/rawgit/blob/master/FAQ.md#how-long-does-the-cdn-cache-files-how-can-i-make-it-refresh-my-file) so it won't reflect further changes to the repo. It's fine for now but if you wanted to show a demo for a newer, improved version it won't work. You'll have to auto-generate the demo to use URLs based on the latest commit hash or a tag.

**Comment by fidian** [comment]
Good to know. I changed the approach to use a `publish` script and just update the `gh-pages` branch with the latest built assets.
