### ISSUE TITLE
atblock_pre/post broken with 0.3.15

### ISSUE THREAD

**Issue by brunob** [fidian/PrettyCSS#52]
This config file https://gist.github.com/brunob/d16beef0f181a55e24b5 doesn't work anymore with 0.3.15 version, seems to have problem with atblock_pre/post :\ It prints things like that : 

```
OUT for block
color: #52a624; 
!!!done`
```

I'm looking to the diff to search the origin of the bug https://github.com/fidian/PrettyCSS/compare/0.3.12...fidian:0.3.15

**Comment by fidian** [comment]
I left debug code in one of my commits. I'm terribly sorry, this is awful.

0.3.16 has been published without the debug code.

**Comment by brunob** [comment]
lol no problem, thx for the fix :)
